{
 "title": "配賦 / ケイパビリティ",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fiscal_year",
    "label": "年度",
    "query": "select distinct(fiscal_year) from business_unit_cost_history order by 1 desc;"
   },
   {
    "name": "capability",
    "query": "SELECT\n    distinct(capability_name)\nFROM\n    stg__master__business_capabilities\nORDER BY 1"
   }
  ]
 },
 "panels": [
  { "title": "内訳", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "配賦の内訳",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cost_pool_name as コストプール,\n  it_tower_name as ITタワー,\n  service_name as サービス,\n  capability_name as ケイパビリティ,\n  sum(allocated_amount) as value\nFROM\n  service_to_capability\nWHERE\n  fiscal_year = $fiscal_year\n  and capability_name = '$capability'\nGROUP BY\n  cost_pool_name,\n  it_tower_name,\n  service_name,\n  capability_name\nORDER BY\n  cost_pool_name,\n  it_tower_name,\n  service_name"
    }
   ]
  },
  { "title": "ルール", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ルール - cost -> tower",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cost_pool_id as cost_pool,\n  it_tower_id as it_tower,\n  sum(allocation_value) as value\nFROM\n  stg__allocations__cost_to_tower \nWHERE\n  fiscal_year = $fiscal_year\nGROUP BY\n  cost_pool_id,\n  it_tower_id\n"
    }
   ]
  },
  {
   "title": "ルール - tower -> service",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  it_tower_id as it_tower,\n  service_id as service,\n  sum(allocation_value) as value\nFROM\n  stg__allocations__tower_to_service \nWHERE\n  fiscal_year = $fiscal_year\nGROUP BY\n  it_tower_id,\n  service_id\n"
    }
   ]
  },
  {
   "title": "ルール - service -> capability",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  service_id as service,\n  capability_id as capability,\n  sum(allocation_value) as value\nFROM\n  stg__allocations__service_to_capability\nWHERE\n  fiscal_year = $fiscal_year\nGROUP BY\n  service_id,\n  capability_id\n"
    }
   ]
  },
  { "title": "Rawデータ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "raw - service_to_capability",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cost_pool_name,\n  cost_sub_pool_name,\n  it_tower_name,\n  it_sub_tower_name,\n  service_name,\n  capability_name,\n  sum(allocated_amount) as allocated_amount\nFROM\n  service_to_capability \nWHERE\n  fiscal_year = $fiscal_year\n  and capability_name = '$capability'\nGROUP BY\n  cost_pool_name,\n  cost_sub_pool_name,\n  it_tower_name,\n  it_sub_tower_name,\n  service_name,\n  capability_name\nORDER BY 1, 2, 3, 4, 5, 6"
    }
   ]
  }
 ]
}