{
 "title": "ビジネス / 部門",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fiscal_year",
    "label": "年度",
    "query": "select distinct(fiscal_year) from business_unit_cost_history order by 1 desc;"
   },
   {
    "name": "business_unit",
    "query": "SELECT\n    distinct(business_unit_name)\nFROM\n    stg__master__business_units\nWHERE\n    parent_id is null\nORDER BY 1"
   }
  ]
 },
 "panels": [
  { "title": "部門", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "予算",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(amount) as value\nFROM\n  stg__entries_plan\nWHERE\n  fiscal_year = $fiscal_year \n  and business_unit_name = '$business_unit'"
    }
   ]
  },
  {
   "title": "実績",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(total_allocated_amount) as value\nFROM\n  business_unit_cost_history\nWHERE\n  fiscal_year = $fiscal_year\n  and business_unit_name = '$business_unit'\nGROUP BY\n  fiscal_year\n"
    }
   ]
  },
  {
   "title": "社員一人あたり",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  unit_cost_per_employee as value\nFROM\n  business_unit_cost_history\nWHERE\n  fiscal_year = $fiscal_year\n  and business_unit_name = '$business_unit'\n"
    }
   ]
  },
  {
   "title": "予実",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  plan_amount as 予算,\n  total_allocated_amount as 実績\nFROM\n  business_unit_cost_history\nWHERE\n  business_unit_name = '$business_unit'\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "社員数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  employee_count as value\nFROM\n  business_unit_cost_history\nWHERE\n  business_unit_name = '$business_unit'\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "社員一人あたり",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  unit_cost_per_employee as value\nFROM\n  business_unit_cost_history\nWHERE\n  business_unit_name = '$business_unit'\nORDER BY\n  1\n"
    }
   ]
  },
  { "title": "サービス", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "サービス - 年度",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  service_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  service_to_business\nWHERE\n  fiscal_year = $fiscal_year\n  and business_unit_name = '$business_unit'\nGROUP BY\n  fiscal_year, fiscal_month, service_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "サービス - 推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_TIMESTAMP(fiscal_year, fiscal_month, 1, 0, 0, 0) as time,\n  service_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  service_to_business\nWHERE\n  business_unit_name = '$business_unit'\nGROUP BY\n  fiscal_year, fiscal_month, service_name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Rawデータ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "raw - service_to_business",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT\n  fiscal_year,\n  fiscal_month,\n  cost_pool_name,\n  cost_sub_pool_name,\n  it_tower_name,\n  it_sub_tower_name,\n  service_name,\n  business_unit_name,\n  employee_count,\n  allocation_value,\n  allocated_amount\nFROM\n  service_to_business\nWHERE\n  fiscal_year = $fiscal_year \n  and business_unit_name = '$business_unit'\nORDER BY 1, 2, 3, 4, 5, 6, 7"
      }
     ]
    }
   ]
  }
 ]
}