{
 "title": "ビジネス / 全社",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fiscal_year",
    "label": "年度",
    "query": "select distinct(fiscal_year) from business_unit_cost_history order by 1 desc;"
   }
  ]
 },
 "panels": [
  { "title": "全社", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "予算",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(amount) as value\nFROM\n  stg__entries_plan\nWHERE\n  fiscal_year = $fiscal_year\nGROUP BY\n  fiscal_year\n"
    }
   ]
  },
  {
   "title": "実績",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(total_allocated_amount) as value\nFROM\n  business_unit_cost_history\nWHERE\n  fiscal_year = $fiscal_year\nGROUP BY\n  fiscal_year\n"
    }
   ]
  },
  {
   "title": "社員一人あたり",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  unit_cost_per_employee as value\nFROM\n  company_cost_history\nWHERE\n  fiscal_year = $fiscal_year\n"
    }
   ]
  },
  {
   "title": "予実",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  plan_amount as 予算,\n  cost_amount as 実績\nFROM\n  company_cost_history\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "社員数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  employee_count as value\nFROM\n  company_cost_history\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "社員一人あたり",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  unit_cost_per_employee as value\nFROM\n  company_cost_history\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "部門",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "部門 - 予実",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  business_unit_name as metric,\n  plan_amount as 予算,\n  total_allocated_amount as 実績\nFROM\n  business_unit_cost_history\nWHERE\n  fiscal_year = $fiscal_year \nORDER BY 3 DESC"
      }
     ]
    },
    {
     "title": "部門 - 予算",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  business_unit_name as metric,\n  plan_amount as value\nFROM\n  business_unit_cost_history\n"
      }
     ]
    },
    {
     "title": "部門 - 実績",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  business_unit_name as metric,\n  total_allocated_amount as value\nFROM\n  business_unit_cost_history\n"
      }
     ]
    },
    {
     "title": "部門 - 社員一人あたり",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  business_unit_name as metric,\n  unit_cost_per_employee as value\nFROM\n  business_unit_cost_history\n"
      }
     ]
    }
   ]
  },
  {
   "title": "ケイパビリティ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "ケイパビリティ - 年度",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  capability_name as metric,\n  total_allocated_amount as 実績\nFROM\n  capability_cost_history\nWHERE\n  fiscal_year = $fiscal_year \nORDER BY 3 DESC"
      }
     ]
    },
    {
     "title": "ケイパビリティ - 推移",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  capability_name as metric,\n  total_allocated_amount as value\nFROM\n  capability_cost_history\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "サービス",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "サービス - 年度",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  service_name as metric,\n  total_allocated_amount as 実績\nFROM\n  service_cost_history\nWHERE\n  fiscal_year = $fiscal_year \nORDER BY 3 DESC"
      }
     ]
    },
    {
     "title": "サービス - 推移",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  service_name as metric,\n  total_allocated_amount as value\nFROM\n  service_cost_history\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "ITタワー",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "ITタワー - 年度",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  it_tower_name as metric,\n  total_allocated_amount as 実績\nFROM\n  tower_cost_history \nWHERE\n  fiscal_year = $fiscal_year \nORDER BY 3 DESC"
      }
     ]
    },
    {
     "title": "ITタワー - 推移",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  it_tower_name as metric,\n  total_allocated_amount as value\nFROM\n  tower_cost_history\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "コストプール",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "コストプール - 年度",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  cost_pool_name as metric,\n  sum(total_amount) as 実績\nFROM\n  cost_pool_history \nWHERE\n  fiscal_year = $fiscal_year \nGROUP BY\n  time, cost_pool_name\nORDER BY 3 DESC"
      }
     ]
    },
    {
     "title": "コストプール - 推移",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  cost_pool_name as metric,\n  sum(total_amount) as value\nFROM\n  cost_pool_history\nGROUP BY\n  time, cost_pool_name\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}