{
 "title": "ビジネス / ケイパビリティ",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fiscal_year",
    "label": "年度",
    "query": "select distinct(fiscal_year) from business_unit_cost_history order by 1 desc;"
   },
   {
    "name": "capability",
    "query": "SELECT\n    distinct(capability_name)\nFROM\n    stg__master__business_capabilities\nORDER BY 1\n"
   }
  ]
 },
 "panels": [
  { "title": "ケイパビリティ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "実績",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(total_allocated_amount) as value\nFROM\n  capability_cost_history\nWHERE\n  fiscal_year = $fiscal_year\n  and capability_name = '$capability'\nGROUP BY\n  fiscal_year\n"
    }
   ]
  },
  {
   "title": "推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(total_allocated_amount) as value\nFROM\n  capability_cost_history \nWHERE\n  capability_name = '$capability'\nGROUP BY\n  time, fiscal_month, capability_name\nORDER BY 1"
    }
   ]
  },
  { "title": "サービス", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "サービス - 年度",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  service_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  service_to_capability\nWHERE\n  fiscal_year = $fiscal_year\n  and capability_name = '$capability'\nGROUP BY\n  fiscal_year, fiscal_month, service_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "サービス - 推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_TIMESTAMP(fiscal_year, fiscal_month, 1, 0, 0, 0) as time,\n  service_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  service_to_capability\nWHERE\n  capability_name = '$capability'\nGROUP BY\n  fiscal_year, fiscal_month, service_name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Rawデータ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "raw - service_to_capability",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\n  fiscal_year,\n  fiscal_month,\n  cost_pool_name,\n  cost_sub_pool_name,\n  it_tower_name,\n  it_sub_tower_name,\n  service_name,\n  capability_name,\n  allocation_value,\n  allocated_amount\nFROM\n  service_to_capability\nWHERE\n  fiscal_year = $fiscal_year \n  and capability_name = '$capability'\nORDER BY 1, 2, 3, 4, 5, 6, 7"
      }
     ]
    }
   ]
  }
 ]
}