{
 "title": "財務 / コストプール",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fiscal_year",
    "label": "年度",
    "query": "select distinct(fiscal_year) from business_unit_cost_history order by 1 desc;"
   },
   {
    "name": "cost_pool",
    "query": "SELECT\n    distinct(cost_pool_name)\nFROM\n    stg__master_tbm__cost_pools\nORDER BY 1"
   }
  ]
 },
 "panels": [
  { "title": "コストプール", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "実績",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(total_amount) as value\nFROM\n  cost_pool_history\nWHERE\n  fiscal_year = $fiscal_year\n  and cost_pool_name = '$cost_pool'\nGROUP BY\n  fiscal_year\n"
    }
   ]
  },
  {
   "title": "推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(total_amount) as value\nFROM\n  cost_pool_history \nWHERE\n  cost_pool_name = '$cost_pool'\nGROUP BY\n  time, fiscal_month\nORDER BY 1"
    }
   ]
  },
  { "title": "サブプール", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "サブプール - 年度",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cost_sub_pool_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  cost_to_tower\nWHERE\n  fiscal_year = $fiscal_year\n  and cost_pool_name = '$cost_pool'\nGROUP BY\n  fiscal_year, fiscal_month, cost_sub_pool_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "サブプール - 推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_TIMESTAMP(fiscal_year, fiscal_month, 1, 0, 0, 0) as time,\n  cost_sub_pool_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  cost_to_tower\nWHERE\n  cost_pool_name = '$cost_pool'\nGROUP BY\n  fiscal_year, fiscal_month, cost_sub_pool_name\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Rawデータ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "raw - cost_to_tower",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\n  fiscal_year,\n  fiscal_month,\n  cost_pool_name,\n  cost_sub_pool_name,\n  sum(allocated_amount) as allocated_amount\nFROM\n  cost_to_tower\nWHERE\n  fiscal_year = $fiscal_year \n  and cost_pool_name = '$cost_pool'\nGROUP BY\n  fiscal_year, fiscal_month, cost_pool_name, cost_sub_pool_name\nORDER BY 1, 2, 3, 4\n"
      }
     ]
    }
   ]
  }
 ]
}