{
 "title": "IT / ITタワー",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fiscal_year",
    "label": "年度",
    "query": "select distinct(fiscal_year) from business_unit_cost_history order by 1 desc;"
   },
   {
    "name": "it_tower",
    "query": "SELECT\n    distinct(it_tower_name)\nFROM\n    stg__master_tbm__it_towers\nORDER BY 1\n\n\n"
   }
  ]
 },
 "panels": [
  { "title": "ITタワー", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "実績",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(total_allocated_amount) as value\nFROM\n  tower_cost_history\nWHERE\n  fiscal_year = $fiscal_year\n  and it_tower_name = '$it_tower'\nGROUP BY\n  fiscal_year\n"
    }
   ]
  },
  {
   "title": "推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(total_allocated_amount) as value\nFROM\n  tower_cost_history \nWHERE\n  it_tower_name = '$it_tower'\nGROUP BY\n  time, fiscal_month\nORDER BY 1"
    }
   ]
  },
  { "title": "サブタワー", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "サブタワー - 年度",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  it_sub_tower_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  cost_to_tower\nWHERE\n  fiscal_year = $fiscal_year\n  and it_tower_name = '$it_tower'\nGROUP BY\n  fiscal_year, fiscal_month, it_sub_tower_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "サブタワー - 推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_TIMESTAMP(fiscal_year, fiscal_month, 1, 0, 0, 0) as time,\n  it_sub_tower_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  cost_to_tower\nWHERE\n  it_tower_name = '$it_tower'\nGROUP BY\n  fiscal_year, fiscal_month, it_sub_tower_name\nORDER BY 1"
    }
   ]
  },
  { "title": "コストプール", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "コストプール - 年度",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cost_pool_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  cost_to_tower\nWHERE\n  fiscal_year = $fiscal_year\n  and it_tower_name = '$it_tower'\nGROUP BY\n  fiscal_year, fiscal_month, cost_pool_name\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "コストプール - 推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAKE_TIMESTAMP(fiscal_year, fiscal_month, 1, 0, 0, 0) as time,\n  cost_pool_name as metric,\n  sum(allocated_amount) as 実績\nFROM\n  cost_to_tower\nWHERE\n  it_tower_name = '$it_tower'\nGROUP BY\n  fiscal_year, fiscal_month, cost_pool_name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Rawデータ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "raw - cost_to_tower",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "rawSql": "SELECT\n  fiscal_year,\n  fiscal_month,\n  cost_pool_name,\n  cost_sub_pool_name,\n  it_tower_name,\n  it_sub_tower_name,\n  allocation_value,\n  allocated_amount\nFROM\n  cost_to_tower\nWHERE\n  fiscal_year = $fiscal_year \n  and it_tower_name = '$it_tower'\nORDER BY 1, 2, 3, 4, 5, 6\n"
      }
     ]
    }
   ]
  }
 ]
}