version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:15
    container_name: tbm-postgres
    environment:
      POSTGRES_USER: tbm_user
      POSTGRES_PASSWORD: tbm_password
      POSTGRES_DB: tbm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tbm_user -d tbm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # dbt (データパイプライン) & dlt (データ収集)
  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tbm-dbt
    volumes:
      - .:/app
    environment:
      DBT_PROFILES_DIR: /app/dbt/files
      DBT_PROJECT_DIR: /app/dbt/src
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: tbm_user
      POSTGRES_PASSWORD: tbm_password
      POSTGRES_DB: tbm_db
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: tail -f /dev/null

  # Grafana (可視化)
  grafana:
    image: grafana/grafana:latest
    container_name: tbm-grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: tbm_user
      DB_PASSWORD: tbm_password
      DB_NAME: tbm_db
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
