FROM python:3.10-slim

WORKDIR /app

# 必要なパッケージをインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
        tzdata git\
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && echo "Asia/Tokyo" > /etc/timezone

# 作業ディレクトリを設定
WORKDIR /app

# コンテナ起動時のコマンド（デフォルトではtail -f /dev/nullで待機）
CMD ["tail", "-f", "/dev/null"]
