# Salesforce認証情報（ダミー値）
[salesforce_data.destination.postgres.credentials]
database = "tbm_db"
username = "tbm_user"
password = "tbm_password"
host = "postgres"
port = 5432

[salesforce_data.source.salesforce.credentials]
api_key = "dummy_api_key_123456789"
client_id = "dummy_client_id_example"
client_secret = "dummy_client_secret_example"
username = "dummy@example.com"
password = "DummyPassword123!"
instance_url = "https://example.my.salesforce.com"


# SAPソース認証情報（ダミー値）
[sap_data.destination.postgres.credentials]
database = "tbm_db"
username = "tbm_user"
password = "tbm_password"
host = "postgres"
port = 5432


# MS365ソース認証情報（ダミー値）
[ms365_data.destination.postgres.credentials]
database = "tbm_db"
username = "tbm_user"
password = "tbm_password"
host = "postgres"
port = 5432


# CRMソース認証情報（ダミー値）
[crm_data.destination.postgres.credentials]
database = "tbm_db"
username = "tbm_user"
password = "tbm_password"
host = "postgres"
port = 5432
